genome: mm39 # hg38 or mm39

cutadapt:
  adapter: AGATCGGAAGA
  extra: ""
# TEsmall parameters
#three_prime_adapter: AGATCGGAAGA # 3' adapter sequence for trimming
#minlen: 16
#maxlen: 36
#maxaln: 100
#threads: 8
#mismatch: 0
#extra_args: ""
